let gameSeq = [];// this array stores the sequence of colors generated by the game
let userSeq = [];// this array stores the sequence of colors clicked by the user

let btncolours = ["yellow", "darkcyan", "crimson", "deepskyblue"]; // this array contains the colors of the buttons

let started = false;
let level = 0;
h2 = document.querySelector("h2");


document.addEventListener("keypress", function(){// this event listener starts the game when any key is pressed
    if (!started){
        alert("Game started");
        started = true;
        levelUp();
    }
})





function gameflash(btn){// this function flashes the button passed to it
    btn.classList.add("flash");
    setTimeout(function(){
        btn.classList.remove("flash");
    },250);
}



function levelUp() {// this function is called when the user successfully completes a level
    userSeq = [];
    level++;
    h2.innerText = `Level ${level}`;
    
    let randIdx = Math.floor(Math.random() * 3);
    let randcolour = btncolours[randIdx];
    let randbtn = document.querySelector(`.${randcolour}`);
    gameSeq.push(randcolour)
    console.log(gameSeq);
    gameflash(randbtn);
}



function checkSequence(idx){// this function checks the users sequence or users last input with the game sequence(game last input)
    // let idx = level-1;
    if (userSeq[idx] === gameSeq[idx]){
        if(userSeq.length === gameSeq.length){
            setTimeout(levelUp, 1000);

        }
        console.log("Same");
    }else{
        h2.innerHTML = `GAME OVER! <br>Your Score was <b> ${level} <b> <br> Press any key to restart`;
        resetGame();
               
        
    }
}



function userpress(){// this function is called when the user clicks on a button
    let btn = this;
   gameflash(btn);
   usercolour = btn.getAttribute("id");
   userSeq.push(usercolour);
   console.log(userSeq);
    checkSequence(userSeq.length-1);
   
}



let Allbtns = document.querySelectorAll(".box");// this selects all the buttons in the game
for (btn of Allbtns){
    btn.addEventListener("click", userpress);
}


function resetGame() { // this function resets the game variables and UI elements
    started = false;
    level = 0;
    gameSeq = [];
    userSeq = [];
}
